# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Everyapi < Formula
  desc "EveryAPI CLI — Claude Code / Codex / Gemini CLI integration + MCP server"
  homepage "https://everyapi.ai"
  version "3.32.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/everyapi-ai/everyapi-ai/releases/download/v3.32.9/everyapi_darwin_amd64.tar.gz"
      sha256 "14b37972988021c279efde0692c3dfb13763965526b9bc3f880e3cfaf1926749"

      define_method(:install) do
        bin.install "everyapi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/everyapi-ai/everyapi-ai/releases/download/v3.32.9/everyapi_darwin_arm64.tar.gz"
      sha256 "03de6ad54c6e451fc1421bc98ea3c20d6443b77ec17f1275e26f23910b3b1a0e"

      define_method(:install) do
        bin.install "everyapi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/everyapi-ai/everyapi-ai/releases/download/v3.32.9/everyapi_linux_amd64.tar.gz"
      sha256 "b6c63f4f5a89c206f7193ffab89268ba5e55584c3ab0637a84ea3a950224d65c"
      define_method(:install) do
        bin.install "everyapi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/everyapi-ai/everyapi-ai/releases/download/v3.32.9/everyapi_linux_arm64.tar.gz"
      sha256 "d2391b564a358e7737301809abf41d7ccf1442d4650bfb7c261464a249a04ef4"
      define_method(:install) do
        bin.install "everyapi"
      end
    end
  end

  test do
    assert_match "everyapi", shell_output("#{bin}/everyapi version")
    output = pipe_output("#{bin}/everyapi mcp",
      %({"jsonrpc":"2.0","id":1,"method":"initialize","params":{}}\n),
      0)
    assert_match "2024-11-05", output
  end
end
