# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Everyapi < Formula
  desc "EveryAPI CLI — Claude Code / Codex / Gemini CLI integration + MCP server"
  homepage "https://everyapi.ai"
  version "3.32.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/everyapi-ai/everyapi-ai/releases/download/v3.32.8/everyapi_darwin_amd64.tar.gz"
      sha256 "1b59aeda6283055300f8b49f00791628f6f765ebf78a71ae500c7031d8209a2b"

      define_method(:install) do
        bin.install "everyapi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/everyapi-ai/everyapi-ai/releases/download/v3.32.8/everyapi_darwin_arm64.tar.gz"
      sha256 "134663420948740d85021819f121e7031f9778238115ea89a6b9e4ac302baec8"

      define_method(:install) do
        bin.install "everyapi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/everyapi-ai/everyapi-ai/releases/download/v3.32.8/everyapi_linux_amd64.tar.gz"
      sha256 "dbc817b6ed30c496b06086235ad65fe71edb342c7642b2fd3957c2c276050d1b"
      define_method(:install) do
        bin.install "everyapi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/everyapi-ai/everyapi-ai/releases/download/v3.32.8/everyapi_linux_arm64.tar.gz"
      sha256 "26818c058b8aad7734ed704ceaa64c9964a007f2f308e47fde3ece9f70cebf6b"
      define_method(:install) do
        bin.install "everyapi"
      end
    end
  end

  test do
    assert_match "everyapi", shell_output("#{bin}/everyapi version")
    output = pipe_output("#{bin}/everyapi mcp",
      %({"jsonrpc":"2.0","id":1,"method":"initialize","params":{}}\n),
      0)
    assert_match "2024-11-05", output
  end
end
