# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Everyapi < Formula
  desc "EveryAPI CLI — Claude Code / Codex / Gemini CLI integration + MCP server"
  homepage "https://everyapi.ai"
  version "3.32.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/everyapi-ai/everyapi-ai/releases/download/v3.32.6/everyapi_darwin_amd64.tar.gz"
      sha256 "9cb8da8cdb6340ceb789d274554c3f01e4ede23d81ef211d429dc1ca055697d0"

      define_method(:install) do
        bin.install "everyapi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/everyapi-ai/everyapi-ai/releases/download/v3.32.6/everyapi_darwin_arm64.tar.gz"
      sha256 "4c1e2362e964883cf48614bfc163550c0effe4a27937881b6467e5641f7e7a01"

      define_method(:install) do
        bin.install "everyapi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/everyapi-ai/everyapi-ai/releases/download/v3.32.6/everyapi_linux_amd64.tar.gz"
      sha256 "b69302783795b0e4ebab138fdf4aab9ccd58b0656a42f7942c1f54498a0d6251"
      define_method(:install) do
        bin.install "everyapi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/everyapi-ai/everyapi-ai/releases/download/v3.32.6/everyapi_linux_arm64.tar.gz"
      sha256 "8dcc29763e73a63efe2e25218ce229c6f5ec4d1eee26e1b3ce248c32e6589aab"
      define_method(:install) do
        bin.install "everyapi"
      end
    end
  end

  test do
    assert_match "everyapi", shell_output("#{bin}/everyapi version")
    output = pipe_output("#{bin}/everyapi mcp",
      %({"jsonrpc":"2.0","id":1,"method":"initialize","params":{}}\n),
      0)
    assert_match "2024-11-05", output
  end
end
